name: CI/CD Pipeline Configuration

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint code
        run: echo "Linting repository"

      - name: Run unit tests
        run: echo "Running unit tests"

  build-and-push-ecr-image:
    runs-on: ubuntu-latest
    needs: integration
    outputs:
      image-pushed: ${{ steps.build-image.outputs.image-pushed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@24d32ffd492484c1d75e0c0b894501ddb9d30d62
        with:
          files: |
            Dockerfile
            requirements.txt
            application.py
            README.md
      
      - name: Set up Docker Buildx
        if: steps.changed-files.outputs.any_changed == 'True' || github.event_name == 'workflow_dispatch'
        uses: docker/setup-buildx-action@v3

      - name: Install Utilities
        if: steps.changed-files.outputs.any_changed == 'True' || github.event_name == 'workflow_dispatch'
        run: |
          sudo apt-get update
          sudo apt-get install -y jq unzip
      
      - name: Configure AWS Credentials
        if: steps.changed-files.outputs.any_changed == 'True' || github.event_name == 'workflow_dispatch'
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Login to Amazon ECR
        id: login-ecr
        if: steps.changed-files.outputs.any_changed == 'True' || github.event_name == 'workflow_dispatch'
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        if: steps.changed-files.outputs.any_changed == 'True' || github.event_name == 'workflow_dispatch'
        id: build-image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry}}
          REPOSITORY: ${{ secrets.AWS_REPOSITORY_NAME }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker buildx build --push \
            --platform linux/amd64 \
            -t $REGISTRY/$REPOSITORY:latest \
            -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        

  continuous-deployment:
    runs-on: ubuntu-latest
    needs: build-and-push-ecr-image
    if: needs.build-and-push-ecr-image.outputs.image-pushed == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Pull latest images
        run: |
          docker pull ${{ secrets.AWS_ECR_LOGIN_URI }}/${{ secrets.AWS_REPOSITORY_NAME }}:latest
      
      - name: Run Docker Image to serve users
        run: |
          docker run -d -p 80:80 --ipc="host" --name mlops/studentperformance -e 'AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}' -e 'AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}' -e 'AWS_REGION=${{ secrets.AWS_REGION }}' ${{ secrets.AWS_ECR_LOGIN_URI }}/${{ secrets.AWS_REPOSITORY_NAME }}:latest
      
      - name: Verify Deployment
        run: |
          sleep 10
          curl -f http://localhost || exit 1
          echo "Deployment successful"
      
      - name: Clean previous images and containers
        run: |
          docker system prune -f
